name: pages
on: [push]
jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          python-version: "3.12"
      - run: |
          conda install -c conda-forge -y voici
      - run: |
          unzip -P my-little-secret export.zip
      - run: |
          cd export
          voici export.ipynb
      - run: |
          ls -lah
          ls -lah export
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: export/_output

  deploy-pages:
    if: ${{ contains(github.ref, 'main') || startsWith(github.ref, 'refs/tags/v') }}
    needs: [build-pages]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
